### PR TITLE
updating cactus formulae

### PR DESCRIPTION
**Pull request by thiagogenez**
Cactus compilation becomes easier after the removal of Kyoto stuffs from versions >= 2.0

### CODE REVIEW

**Comment by thiagogenez** [comment]
The errors regarding
```
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html
```
can be solved after the approval of #50

**Comment by thiagogenez** [comment]
Errors regarding 
```
curl: (22) The requested URL returned error: 502 Bad Gateway
```
are raised because the `linuxbrew-core`'s formulas  when `HOMEBREW_VERSION=1.9.3` relies on a server that is not available to download the sources codes, i.e.,  https://linuxbrew.bintray.com/bottles/

@marcoooo - I believe an upgrading plan is needed for this case. At the moment, every `ensembl/homebrew-X` relies on a single [Docker image](https://github.com/muffato/docker-ensembl-linuxbrew-basic-dependencies/blob/master/Dockerfile) for Travis checks. In this case, would be better that each `ensembl/homebrew-X` uses their own Docker image?

**Comment by marcoooo** [comment]
@thiagogenez I can't tell you, I am usually not implicated too much with homebrew configuration.

**Comment by thiagogenez** [comment]
> @thiagogenez I can't tell you, I am usually not implicated too much with homebrew configuration.

No worries. I'm thinking of a solution and propose along with this PR for Cactus compilation and then we can discuss later with (I believe) with @thibauthourlier ?

**Comment by thiagogenez** [comment]
@marcoooo, this PF also proposes a modification in the Docker image to use Linuxbrew `3.1.0`, the same version installed in our cluster. I haven't checked the impact of this on other formulas of this repo yet.

**Comment by marcoooo** [comment]
> @marcoooo, this PF also proposes a modification in the Docker image to use Linuxbrew `3.1.0`, the same version installed in our cluster. I haven't checked the impact of this on other formulas of this repo yet.

@thiagogenez  Should I wait for your checks before merging then?

**Comment by thiagogenez** [comment]
> > @marcoooo, this PF also proposes a modification in the Docker image to use Linuxbrew `3.1.0`, the same version installed in our cluster. I haven't checked the impact of this on other formulas of this repo yet.
> 
> @thiagogenez Should I wait for your checks before merging then?

Yes, please. I will check all the formulas of this repo and let you know. Regarding the formulas of others ensembl's homebrew repo `ensembl/homebrew-?`, they need to check separated.

**Comment by thibauthourlier** [comment]
First this PR will need to be closed and recreated against `feature/codon_cluster`

I don't think multiple Dockerfiles are needed as Matthieu's code is making sure to have all the data needed. And some formulas need code from the other ensembl/homebrew-* repos.
I need to put the currently used Dockerfile in a repo under Ensembl and have it under our docker org.

The new PR only need the updates to the cactus file

**Review by marcoooo — CHANGES_REQUESTED** [review]
As mentioned by @thibauthourlier this PR need to go against `feature/codon_cluster`

**Comment by thiagogenez** [comment]
Thank @marcoooo and @thibauthourlier for the comments. I hope to finish this soon - sorry for the delay.

**Comment by marcoooo** [comment]
Rendered obsolete now we have new environment setup

**Pull request closed without merging**
